### ISSUE TITLE
Re-generalize convert_to_gromacs to handle more than two components

### ISSUE THREAD

**Issue by davidlmobley** [MobleyLab/SolvationToolkit#19]
When convert_to_gromacs was finished to resolve issue #8 and #3 (by PR #15) it was assumed that the number of components in the system was two, i.e. in the case of selecting a single monomer of one component (present with quantity more than one) we have:

```
self.n_monomers = [self.n_monomers[0]] + [1] + [self.n_monomers[1]]
```

which is only correct if self.n_monomers originally has only two elements.

This code needs to be generalized (as I had attempted to when I originally drafted it) to handle the case where we might have three or more components in the system, i.e.

```
builder = MixtureSystem( [ 'phenol', 'toluene', 'cyclohexane'], [phenol_smiles, toluene_smiles, cyclohexane_smiles], [3, 5, 40] )
```

@nividic , can you address this? It's not critical for the undergrads (they are looking at two-component systems at present) but we'll need it eventually.

**Comment by nividic** [comment]
You should close this one.
