### ISSUE TITLE
Add ParmEd Version Check

### ISSUE THREAD

**Issue by bannanc** [MobleyLab/SolvationToolkit#34]
As discussed in group meeting, here is how I checked the version in the Hydroxynator:

    # If ParmEd is older than 2.0.4 then it will not work, raise an error
    try:
        ver = parmed.version
    except:
        oldParmEd = Exception('ERROR: ParmEd is too old, please upgrade to 2.0.4 or later')
        raise oldParmEd
    if ver < (2,0,4):
        raise RuntimeError("ParmEd is too old, please upgrade to 2.0.4 or later")

**Comment by davidlmobley** [comment]
Made an update to a branch which should fix this.
