### ISSUE TITLE
Get OpenEye tools working on travis so tests can be more thorough

### ISSUE THREAD

**Issue by davidlmobley** [MobleyLab/SolvationToolkit#49]
Ultimately, we need to get the OpenEye tools working so our tests can involve actually generating all files rather than just starting from pre-existing `.mol2` files, etc.

**Comment by davidlmobley** [comment]
@jchodera - are you able to give us pointers on how to get the OpenEye tools working for testing via Travis? I know this is working on openmoltools.

**Comment by jchodera** [comment]
Feel free to steal shamelessly from `openmoltools` for the `.travis.yml` file.  Once you have this set up, I can walk you through the steps of encrypting your own OpenEye license file and checking that in.

It goes without saying, but do NOT check in your unencrypted OpenEye license file!

**Comment by davidlmobley** [comment]
@jchodera - I have travis working with `.yaml` files now in #55, and it can install the OpenEye tools, so I think the next step is for me to deal with the encrypted license file. Can you give some pointers on how to do this, or is it documented somewhere? I can't find anything immediately obvious with Google.

**Comment by davidlmobley** [comment]
Ah, is it this? https://docs.travis-ci.com/user/encrypting-files/

**Comment by davidlmobley** [comment]
Yes, that looks like exactly it - see https://github.com/choderalab/openmoltools/issues/136#issuecomment-117875446 where this was discussed. OK, I HOPEFULLY can figure out how to do this now.

**Comment by jchodera** [comment]
Yes, you found it!  Let me know if you have trouble and I can walk you through it on slack

**Comment by davidlmobley** [comment]
Closed via #55 . Thanks!
