### ISSUE TITLE
Check interface with other OpenForcefield initiative collaborators

### ISSUE THREAD

**Issue by davidlmobley** [MobleyLab/SolvationToolkit#53]
@jchodera , @mrshirts - I wanted to confirm that you guys are happy with the interface here for creating inputs for simulations of arbitrary mixtures. Currently one invokes the `MixtureSystem` class and provides a list of compound labels (used for filenames, etc.), a list of isomeric SMILES strings, a list of the number of monomers of each which are desired, and a data path. So using it looks something like this:
```
builder = MixtureSystem(  [ 'phenol', 'toluene', 'cyclohexane'], ['c1ccc(cc1)O', 'Cc1ccccc1', 'C1CCCCC1'], [ 1, 10, 500], 'data/' )
builder.run( just_build = True )
```

By default it provides AMBER `.prmtop` and `.crd` files for all components as well as for the solvated system; `.mol2` files for the components are also provided. Additionally, `.sdf` files of the components with our planned custom SDF tags (`partial_charges`, `partial_bond_orders`) are provided; we're adding the `atom_types` tag as well. 

Anything else you'd like to see?

**Comment by jchodera** [comment]
That constructor seems a little weird due to the various lists---someone will have to make sure all the arguments correspond to the same position in each list.  What about something like this?
```python
mixture = MixtureSystem()
mixture.addComponent(name='phenol', smiles='c1ccc(cc1)O', number=1)
mixture.addComponent(name='toluene', smiles='Cc1ccccc1', number=10)
mixture.addComponent(name='cyclohexane', smiles='C1CCCCC1', number=500)
mixture.build(prmtop_filename='mixture.prmtop', inpcrd_filename='mixture.inpcrd')
```
The `build()` function could take a bunch of optional arguments for which files you want to write out (PDB, prmtop, inpcrd, mol2, SDF).

**Comment by davidlmobley** [comment]
Ah, that's probably a good idea. 

Currently in practice what we typically do is specify a list of names or smiles and counts and then generate the other info from those (i.e. see example https://github.com/MobleyLab/SolvationToolkit/blob/master/scripts/start.py, which specifies a list of solute molecule names and a list of solvent molecule names, then generates SMILES for all of them and puts one solute molecule into 800 solvent molecules for each). 

I think ultimately either approach foists the "make sure your (label, smiles, number) sets are ordered" issue onto the user (there is no other way). But your approach makes it more clear that these have to have the same order, so it seems likely it will reduce the possibility of user error.

@mrshirts - any other thoughts? Or @bannanc , @camizanette ? @bmanubay?

**Comment by jchodera** [comment]
> Currently in practice what we typically do is specify a list of names or smiles and counts and then generate the other info from those

So you would instead do something like this:
```python
for solute in solutes:
   for solvent in solvents:
      mixture = MixtureSystem()
      mixture.addComponent(name=solute, smiles=get_smiles(solute), number=N_solute)
      mixture.addComponent(name=solvent, smiles=get_smiles(solvent), number=N_solvent)
      prefix = solute + '-' + solvent
      mixture.build(prmtop_filename=preifx+'.prmtop', inpcrd_filename=prefix+'.inpcrd')
```

**Comment by davidlmobley** [comment]
Yup, though note that I'm actually referring to these as "labels" rather than names. Generally, names actually make horrible labels because they potentially contain a wide variety of special characters which can cause problems for the tools involved in some cases. Most of our tools actually can cope (because they take whatever the input names are and modify them to well-behaved temporary names while manipulating them) but in my experience, using chemical names as file names always results in problems somewhere down the line. (Think of a filename containing spaces, commas, and square and curly brackets... It requires special handling which is different in Python versus the command line.)

As noted, I've actually paid attention to this in working on a lot of our tools, i.e. in `openmoltools`, so many will handle these correctly. BUT, I still don't recommend it. :)

**Comment by davidlmobley** [comment]
In other words, we'd be going with something more like:

```
mixture.addComponent(label=solute, smiles=get_smiles(solute), number=N_solute)
```

**Comment by jchodera** [comment]
Sounds good!

**Comment by davidlmobley** [comment]
@mrshirts - any thoughts?

**Comment by davidlmobley** [comment]
In the discussion over here: https://github.com/open-forcefield-group/open-forcefield-tools/issues/1#issuecomment-221703530 I noticed that it would probably be easier to manage this if the user didn't even have to think about how many molecules to use; we can bake in a "system size" estimator and just have the user specify mole fraction of each component, i.e.:
```python
mixture.addComponent(label=solute, smiles=get_smiles(solute), mole_fraction=0.3)
```
The `mole_fraction` option could be overridden by manually specifying the number of molecules of each, or something similar to that.

**Comment by davidlmobley** [comment]
As per discussion with JDC on the other issue, we'll generalize this to look more like this:
```python
liquid = Mixture()
liquid.addComponent('water')

binary_mixture = Mixture()
binary_mixture.addComponent('water', mole_fraction=0.2)
binary_mixture.addComponent('methanol') # assumed to be rest of mixture if no mole_fraction specified

ternary_mixture = Mixture()
binary_mixture.addComponent('ethanol', mole_fraction=0.2)
binary_mixture.addComponent('methanol', mole_fraction=0.2)
ternary_mixture.addComponent('water')

infinite_dilution = Mixture()
infinite_dilution.addComponent('phenol', mole_fraction=0.0) # infinite dilution
infinite_dilution.addComponent('water')
```

**Comment by davidlmobley** [comment]
Closing this discussion as we begin implementing in #60
