### ISSUE TITLE
Import issue, not detecting ParmEd

### ISSUE THREAD

**Issue by bmanubay** [MobleyLab/SolvationToolkit#62]
Hopefully just a quick/small issue, but I'm getting some errors while importing `solvationtoolkit` with `parmed` not being detected correctly. I'm using Anaconda 2 and the Spyder IDE. Here's the traceback I'm getting:

`>>import solvationtoolkit`
`Traceback(most recent call last):`

  `File "<ipython-input-24-e1184cf7ccca>", line 1, in <module>`
    `import solvationtoolkit`

  `File "/home/bmanubay/anaconda2/lib/python2.7/site-packages/solvationtoolkit-0.2.4.dev0-` `py2.7.egg/solvationtoolkit/__init__.py", line 29, in <module>`
    `from solvationtoolkit import solvated_mixtures`

  `File "/home/bmanubay/anaconda2/lib/python2.7/site-packages/solvationtoolkit-0.2.4.dev0-` `py2.7.egg/solvationtoolkit/solvated_mixtures.py", line 43, in <module>`
    `raise RuntimeError("ParmEd is too old, please upgrade to 2.5.1 or later")`

`RuntimeError: ParmEd is too old, please upgrade to 2.5.1 or later`

`>>import parmed`

`>>print parmed.__version__`
`2.5.1`

Clearly, the version of parmed is up to date, so I'm not really sure what the issue is. I've tried uninstalling and reinstalling parmed with no luck. Any thoughts?

**Comment by davidlmobley** [comment]
I had a look. Sorry about that. This is a "bad debug info" bug from me. There is a bug in, er, OpenEye's `.mol2` format which is bypassed in the development version of ParmEd. You will need to 'conda install parmed-dev', I believe, OR pull it down the "old fashioned" way and "python setup.py install" it. Really you need at least version 2.5.1.10, which is not yet released.

So, bsaically, the error message should say, "ParmEd is too old, please upgrade to 2.5.1.10 or later".

See https://github.com/ParmEd/ParmEd/issues/698

**Comment by bmanubay** [comment]
That did indeed solve the issue. Thanks David!
