### ISSUE TITLE
Supports RDKit

### ISSUE THREAD

**Issue by iwatobipen** [MobleyLab/SolvationToolkit#88]
Dear developer,

I would like to ask you that do you have plan to support RDKit for structure handling in the package like openffTK?
Thanks,

Taka

**Comment by davidlmobley** [comment]
Good question, but the answer is that I'm not really maintaining this at present. Instead, I recently discovered that we have functionality in OpenFF's Evaluator which can do the same thing (in a way which should work with RDKit). Would that be helpful to you? If so I can link you to how that works and provide an example.

**Comment by iwatobipen** [comment]
Thanks for your reply and sorry for my late reply.
I'll try to use the Evaluator ;)

**Comment by MiloszGrabski** [comment]
> Good question, but the answer is that I'm not really maintaining this at present. Instead, I recently discovered that we have functionality in OpenFF's Evaluator which can do the same thing (in a way which should work with RDKit). Would that be helpful to you? If so I can link you to how that works and provide an example.

Hi,
Would you be able to provide either link to documentation or an example?
I keep digging but unable to find anything useful.
Cheers,
M

**Comment by davidlmobley** [comment]
Potentailly. I have an example of this in a course I teach, e.g. this Jupyter notebook here: https://github.com/MobleyLab/drug-computing/blob/f38a4148e9e70238c88fc8110d95b34688f02838/uci-pharmsci/lectures/SMIRNOFF_simulations/mixture_simulations.ipynb (probably won't load in a web browser but consider cloning the repo and looking at the mixture_simulations notebook).
